### ISSUE TITLE
ModuleNotFoundError: No module named 'ui.dialog6

### ISSUE THREAD

**Issue by look1z** [DanielRWong/91porn-downloader#1]
直接运行了start.py报错

Traceback (most recent call last):
  File "start.py", line 7, in <module>
    from ui.downloader_ui import MainWindow
  File "D:\ctfd\91porn-downloader\ui\downloader_ui.py", line 22, in <module>
    from ui.dialog6 import Ui_Dialog as Ui_Dialog6
ModuleNotFoundError: No module named 'ui.dialog6'

看了下项目内容，没有dialog6，downloader_ui里对dialog6做了引用

**Comment by DanielRWong** [comment]
不好意思，一直没看issue。把用到dialog6的地方注释掉就行。我已经更新了。
