### ISSUE TITLE
递归错误

### ISSUE THREAD

**Issue by 1elmarco** [DanielRWong/91porn-downloader#4]
2022-01-04 09:00:45,290 INFO Make output dir F:/20211207
Traceback (most recent call last):
  File "start.py", line 19, in <module>
    run()
  File "start.py", line 11, in run
    check_output_path()
  File "E:\91porn-downloader-main\utils\path.py", line 16, in check_output_path
    make_path(output_path)
  File "E:\91porn-downloader-main\utils\path.py", line 21, in make_path
    make_path(path_tuple[0])
  File "E:\91porn-downloader-main\utils\path.py", line 21, in make_path
    make_path(path_tuple[0])
  File "E:\91porn-downloader-main\utils\path.py", line 21, in make_path
    make_path(path_tuple[0])
  [Previous line repeated 991 more times]
  File "E:\91porn-downloader-main\utils\path.py", line 19, in make_path
    path_tuple = os.path.split(path)
  File "C:\Users\Administrator\anaconda3\lib\ntpath.py", line 186, in split
    seps = _get_bothseps(p)
  File "C:\Users\Administrator\anaconda3\lib\ntpath.py", line 35, in _get_bothseps
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by 1elmarco** [comment]
问题解决
